### ISSUE TITLE
Generate track based on .geojson file

### ISSUE THREAD

**Issue by ebbanat** [Zijji/HVCCC_Visualisation#16]
~~-Pre: Trim the train network to be in Australia~~
![board](https://user-images.githubusercontent.com/16621776/64148743-63090680-ce67-11e9-8b73-443f35a181ed.png)
~~Current: Understand the file standard~~
Current: Draw lines in Unity
Post: Turn 'lines' into a NavMesh

**Comment by ebbanat** [comment]
@lachlangreenXD we will probably collab on this on friday. If you have any questions send them over.

**Comment by ebbanat** [comment]
Eventually make it into a NavMesh

**Comment by ebbanat** [comment]
Created a .dxf file that only contains the hunter valley trains. need to double check with chris if they are the right boundaries / extents.

**Comment by ebbanat** [comment]
Just figured out that QGIS3.4 can export to a GeoJSON format. Using that now.

**Comment by ebbanat** [comment]
Proper boundaries for the Hunter Valley Tracks (both in KML and GeoJSON format)

**Comment by chrischapman1** [comment]
Have you confirmed geojson can make GameObject?

**Comment by ebbanat** [comment]
> Have you confirmed geojson can make GameObject?

Me and lochy are working on that now.

**Comment by ebbanat** [comment]
@lachlangreenXD finish up XML.
@ebbanat put it into unity (Will do this monday)
